// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5uMNME9_y4Am26THM_XoDyYXnZ9JeaSo',
    appId: '1:130943813995:web:fc16b2480c8e3736f1242e',
    messagingSenderId: '130943813995',
    projectId: 'fir-flutter-codelab-8a2ae',
    authDomain: 'fir-flutter-codelab-8a2ae.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-8a2ae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWmBwtlyR3BsXfI4ril3zpfWKstc-fErY',
    appId: '1:130943813995:android:7d1bb68c339092aff1242e',
    messagingSenderId: '130943813995',
    projectId: 'fir-flutter-codelab-8a2ae',
    storageBucket: 'fir-flutter-codelab-8a2ae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9kGYElsKpvuQ9I67e6qcBKTqwK68S7P8',
    appId: '1:130943813995:ios:a777282b2dee0c66f1242e',
    messagingSenderId: '130943813995',
    projectId: 'fir-flutter-codelab-8a2ae',
    storageBucket: 'fir-flutter-codelab-8a2ae.appspot.com',
    iosClientId: '130943813995-f4m50t8skos6qf5p4vt62t1b2fc5skqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9kGYElsKpvuQ9I67e6qcBKTqwK68S7P8',
    appId: '1:130943813995:ios:a777282b2dee0c66f1242e',
    messagingSenderId: '130943813995',
    projectId: 'fir-flutter-codelab-8a2ae',
    storageBucket: 'fir-flutter-codelab-8a2ae.appspot.com',
    iosClientId: '130943813995-f4m50t8skos6qf5p4vt62t1b2fc5skqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
